# Generated by Django 5.0.1 on 2024-01-23 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('key_href', models.URLField()),
                ('level', models.IntegerField()),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('playable_class_id', models.IntegerField()),
                ('playable_class_href', models.URLField()),
                ('playable_race_id', models.IntegerField()),
                ('playable_race_href', models.URLField()),
                ('realm_id', models.IntegerField()),
                ('realm_key_href', models.URLField()),
                ('realm_slug', models.CharField(max_length=100)),
                ('rank', models.IntegerField()),
                ('meta', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
