# Generated by Django 5.0.1 on 2024-01-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characters',
            name='level',
            field=models.IntegerField(blank=True),
        ),
    ]
