# Generated by Django 5.0.1 on 2024-01-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
