# Generated by Django 5.0.1 on 2024-01-28 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowbot', '0002_alter_characters_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='BnetTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
            ],
        ),
    ]
