# Generated by Django 5.0.1 on 2024-01-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowbot', '0003_bnettokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='bnettokens',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
